services:
  web:
    build: .
    command: gunicorn espnet.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    expose:
      - 8000
    environment:
      DB_HOST: db
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: espnet_db
      POSTGRES_USER: espnet_user
      POSTGRES_PASSWORD: espnet_password
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/staticfiles
    depends_on:
      - web

volumes:
  postgres_data: