# Generated by Django 4.2.30 on 2026-04-11 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStatSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('win_rate', models.FloatField(default=0.0)),
                ('kd_ratio', models.FloatField(default=0.0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_history', to='users.playerprofile')),
            ],
            options={
                'unique_together': {('player', 'date')},
            },
        ),
    ]
