# Generated by Django 4.2.30 on 2026-04-11 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scrim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField()),
                ('format', models.CharField(help_text='e.g. BO1, BO3', max_length=50)),
                ('status', models.CharField(choices=[('open', 'Open'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opponent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_scrims', to='teams.team')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_scrims', to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='MatchDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_score', models.IntegerField(default=0)),
                ('opponent_score', models.IntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('mvp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.playerprofile')),
                ('scrim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_details', to='scrims.scrim')),
            ],
        ),
    ]
